[package]
name = "serde"
version = "0.1.0"
edition = "2021"

[dependencies]
awheel = { workspace = true, features = ["serde"] }
postcard = { version = "1.0.0", features = ["alloc"] }
lz4_flex = { version = "0.11", default-features = false }
