[workspace]
resolver = "1" # needed for haw_demo to work on web
members = [
    "crates/*",
    "benchmarks/*"
]

[workspace.package]
authors = ["Max Meldrum <max@meldrum.se>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = 2 # fast and small wasm

[workspace.dependencies]
haw = { path = "crates/haw", version = "0.1.0" }
fiba_rs = { path = "crates/fiba_rs", version = "0.1.0" }

sketches-ddsketch = "0.1"
minstant = "0.1"
fastrand = "1.8.0"
rand = "0.8.5"
hdrhistogram = "7"
clap = { version = "3.2", features = ["derive"] }
criterion = "0.4"