[package]
name = "haw"
version = "0.1.0"
edition = "2021"
categories = ["index", "temporal warehousing", "streaming", "no-std"]
authors = ["Max Meldrum <max@meldrum.se>"]
readme = "README.md"
license = "Apache-2.0 & MIT"

[package.metadata.docs.rs]
all-features = true
targets = []
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["years_size_10", "std"]
alloc = ["hashbrown", "rkyv?/alloc"]
std = ["alloc", "rkyv?/std"]
years_size_10 = []
years_size_100 = []
drill_down = ["alloc"]
rkyv = ["dep:rkyv"]

[dependencies]
rkyv = { version = "0.7.39", default-features = false, features = ["size_32", "copy", "copy_unsafe"], optional = true }
hashbrown = { version = "0.13", optional = true }

[dev-dependencies]
fastrand = "1.8.0"
rand = "0.8.5"
criterion = "0.4"
lz4_flex = "0.9.5"

[[example]]
name = "serde"
path = "examples/serde.rs"
required-features = ["rkyv", "std"]

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "advance"
harness = false

[[bench]]
name = "queries"
harness = false

[[bench]]
name = "merge"
harness = false

[[bench]]
name = "serde"
harness = false
required-features = ["rkyv"]
