[package]
name = "wheeldb"
version = "0.1.0"
edition = "2021"
authors = ["Max Meldrum <max@meldrum.se>"]
license = "Apache-2.0 & MIT"


[dependencies]
haw = { path = "../haw", features = ["rkyv"] }
time = { version = "0.3.17", default-features = false }
smallvec = "1.10.0"
parking_lot = "0.12.1"
crc32fast = "1.3.2"
lz4_flex = "0.9.5"
arrow2 = { version = "0.17.0", features = ["compute_aggregate", "compute_arithmetics", "simd"] }


# https://github.com/tikv/jemallocator/blob/52de4257fab3e770f73d5174c12a095b49572fba/jemalloc-sys/build.rs#L26-L27
[target.'cfg(any(target_os = "openbsd", target_env = "msvc"))'.dependencies.rocksdb]
default-features = false
features = ["lz4"]
version = "0.20.1"

[target.'cfg(not(any(target_os = "openbsd", target_env = "msvc")))'.dependencies.rocksdb]
default-features = false
features = ["lz4", "jemalloc"]
version = "0.20.1"