[package]
name = "window"
version = "0.1.0"
edition.workspace = true

[dependencies]
haw = { workspace = true, features = ["window", "stats", "sync"] }
fiba_rs.workspace = true
clap.workspace = true
fastrand.workspace = true
hdrhistogram.workspace = true
minstant.workspace = true
sketches-ddsketch.workspace = true

[dev-dependencies]
rand.workspace = true
criterion.workspace = true
fastrand.workspace = true

[[bench]]
name = "insert"
harness = false
